server:
  port: 9094

spring:
  application:
    name: ORDER-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://orderuser:123@cluster0.nodgvej.mongodb.net/orderdb?retryWrites=true&w=majority

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true