server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/

spring:
  application:
    name: RESTAURANT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3308/restaurantdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
