server:
  port: 9092

spring:
  application:
    name: USER-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3310/userdb?createDatabaseIfNotExist=true
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
